project3/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'),
]

project3/project3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

project3/blog/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    """カテゴリ"""
    name = models.CharField('カテゴリ名', max_length=255)
    creat_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.name

class Post(models.Model):
    """ブログの記事"""
    title = models.CharField('タイトル', max_length=30)
    text = models.TextField('本文')
    creat_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.title

class Comment(models.Model):
    """ブログのコメント"""
    name = models.CharField('名前', max_length=30, default='名無し')
    text = models.TextField('本文')
    post = models.ForeignKey(Post, verbose_name='紐づく記事', on_delete=models.PROTECT)
    creat_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10] #10文字目までを表示

project3/blog/views.py
from django.views import generic
from django.db.models import Q
from .models import Post, Category, Comment
from django.shortcuts import get_object_or_404, redirect
from .forms import CommentCreateForm

class IndexView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self): #記事を新しい順に並び替え
        queryset = Post.objects.order_by('-creat_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset

class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-creat_at').filter(category=category)
        return queryset

class DetailView(generic.DetailView):
    model = Post

class CommentView(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:detail', pk=post_pk)

project3/blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>ブログ</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'blog:index' %}">ブログ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Home </a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin </a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="jumbotron">
  <h1 class="display-3">雑記帳</h1>
  <p class="lead">日々、感じたことを綴るブログ</p>
  <hr class="my-2">
</div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
            {% for category in category_list %}
            <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class="bg-dark text-white text-center py-3">
      <p>Kanan</p>
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

project3/blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}

  </ul>
</nav>

project3/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in post_list %}
  <div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
    <div class="card-body">
        <p>{{ post.creat_at }}, {{ post.category }}</p>
        <a href="{% url 'blog:detail' post.pk %}" class="btn btn-dark">続きを読む</a>
    </div>
  </div>
{% endfor %}

{% include 'blog/page.html' %}

{% endblock %}